package main

import (
	"encoding/json"
	"log"
	"net/http"
	"time"

	"edgeforge/backend/internal/metrics"
	"edgeforge/backend/internal/middleware"
	"edgeforge/backend/internal/registry"
)

type RequestBody struct {
	Route   string         `json:"route"`
	Payload map[string]any `json:"payload"`
}

type RequestResponse struct {
	RequestID string         `json:"requestId"`
	Route     string         `json:"route"`
	Service   string         `json:"service"`
	RoutedTo  string         `json:"routedTo"`
	TargetURL string         `json:"targetUrl"`
	Status    string         `json:"status"`
	Payload   map[string]any `json:"payload,omitempty"`
}

func writeJSON(w http.ResponseWriter, statusCode int, v any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(statusCode)
	_ = json.NewEncoder(w).Encode(v)
}

func resolveServiceName(route string) string {
	switch route {
	case "/orders":
		return "orders"
	case "/analytics":
		return "analytics"
	default:
		return ""
	}
}

func main() {
	m := metrics.New()
	serviceRegistry := registry.New()
	mux := http.NewServeMux()

	// Health endpoint
	mux.HandleFunc("/health", func(w http.ResponseWriter, r *http.Request) {
		writeJSON(w, http.StatusOK, map[string]any{
			"status":  "ok",
			"service": "edgeforge-gateway",
		})
	})

	// Status endpoint
	mux.HandleFunc("/api/v1/status", func(w http.ResponseWriter, r *http.Request) {
		writeJSON(w, http.StatusOK, m.Snapshot())
	})

	// Request endpoint
	mux.HandleFunc("/api/v1/request", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			writeJSON(w, http.StatusMethodNotAllowed, map[string]any{"error": "method_not_allowed"})
			return
		}

		var body RequestBody
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			m.IncErrors()
			writeJSON(w, http.StatusBadRequest, map[string]any{"error": "invalid_json"})
			return
		}

		// Tracking request count
		m.IncRequests()

		time.Sleep(80 * time.Millisecond)

		// Using requestId generated by middleware
		reqID := middleware.GetRequestID(r)

		serviceName := resolveServiceName(body.Route)
		if serviceName == "" {
			m.IncErrors()
			writeJSON(w, http.StatusBadRequest, map[string]any{
				"error": "unknown_route",
			})
			return
		}

		instances, err := serviceRegistry.GetHealthyInstances(serviceName)
		if err != nil {
			m.IncErrors()
			writeJSON(w, http.StatusBadGateway, map[string]any{
				"error": err.Error(),
			})
			return
		}

		selected := instances[0]

		writeJSON(w, http.StatusOK, RequestResponse{
			RequestID: reqID,
			Route:     body.Route,
			Service:   serviceName,
			RoutedTo:  selected.Name,
			TargetURL: selected.URL,
			Status:    "success",
			Payload:   body.Payload,
		})
	})

	handler := middleware.WithRequestIDAndLogging(mux)

	log.Println("EdgeForge backend running on :8080")
	log.Fatal(http.ListenAndServe(":8080", handler))
}
